#Library

In [ ]:
import numpy as np
import pandas as pd

#Preproccesing

In [ ]:
df = pd.read_csv('Salary Data.csv')
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [ ]:
df.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [ ]:
#Datatypes of features
df.dtypes

Age                    float64
Gender                  object
Education Level         object
Job Title               object
Years of Experience    float64
Salary                 float64
dtype: object

In [ ]:
# Number of all missing datapoints
df.isna().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [ ]:
#Dihapus karena NAN nya di rw yang sama
df.dropna(inplace=True)
df.isna().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [ ]:
df['Education Level'].unique()

array([0, 1, 2])

In [ ]:
df['Job Title'].unique()

## Encoding dan Mencari Nilai korelasi kolom Salary dengan kolom Lainnya

In [ ]:
# One Hot Encoding untuk kolom Job Title
df_encoded = pd.get_dummies(df['Job Title'])

# Hitung korelasi Spearman
correlations = df_encoded.corrwith(df['Salary'], method="spearman")

print(correlations, correlations.max())

Account Manager                -0.025791
Accountant                     -0.046038
Administrative Assistant       -0.077483
Business Analyst               -0.033792
Business Development Manager   -0.009882
                                  ...
UX Designer                    -0.021934
UX Researcher                  -0.033263
VP of Finance                   0.087978
VP of Operations                0.086532
Web Developer                  -0.033263
Length: 174, dtype: float64 0.26812304473552123

In [ ]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])
df["Education Level"] = df["Education Level"].map({"Bachelor's": 0, "Master's": 1, "PhD": 2})

df[['Gender', 'Education Level']]

     Gender  Education Level
0         1                0
1         0                1
2         1                2
3         0                0
4         1                1
..      ...              ...
370       0                0
371       1                1
372       0                0
373       1                0
374       0                2

[373 rows x 2 columns]

In [ ]:
# Menghitung Nilai Korelasi (0..1)
for col in df.columns:
  if col != 'Salary' and (df[col].dtype == 'float64' or df[col].dtype == 'int64'):
    c = df['Salary'].corr(df[col])
    print(f"Korelasi Kolom {col} dan Kolom Salary: {c}")

Korelasi Kolom Age dan Kolom Salary: 0.9223352439166439
Korelasi Kolom Gender dan Kolom Salary: 0.07110555689962005
Korelasi Kolom Education Level dan Kolom Salary: 0.6703707245252968
Korelasi Kolom Years of Experience dan Kolom Salary: 0.9303377227618355

In [ ]:
# Menghitung korelasi menggunakan metode Kendall
df.corr(method='kendall')

<ipython-input-130-f338f1862aa3>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr(method='kendall')

,Age,Gender,Education Level,Years of Experience,Salary
Age,1.000000,-0.016855,0.445003,0.914417,0.800974
Gender,-0.016855,1.000000,-0.045885,-0.006152,0.052202
Education Level,0.445003,-0.045885,1.000000,0.470249,0.542441
Years of Experience,0.914417,-0.006152,0.470249,1.000000,0.824300
Salary,0.800974,0.052202,0.542441,0.824300,1.000000

In [ ]:
# Drop kolom non relevan
df.drop(['Job Title'],axis=1,inplace=True)
df.drop(['Gender'], axis=1, inplace=True)

In [ ]:
df

      Age  Education Level  Years of Experience    Salary
0    32.0                0                  5.0   90000.0
1    28.0                1                  3.0   65000.0
2    45.0                2                 15.0  150000.0
3    36.0                0                  7.0   60000.0
4    52.0                1                 20.0  200000.0
..    ...              ...                  ...       ...
370  35.0                0                  8.0   85000.0
371  43.0                1                 19.0  170000.0
372  29.0                0                  2.0   40000.0
373  34.0                0                  7.0   90000.0
374  44.0                2                 15.0  150000.0

[373 rows x 4 columns]

## Linear Regression

In [ ]:
from sklearn import metrics
import seaborn as seabornInstance
from sklearn.model_selection import train_test_split
from statsmodels.regression.linear_model import OLS

In [ ]:
# Target
Y =pd.DataFrame(df[df.columns[-1]])
# Input
X =pd.DataFrame(df.drop(df.columns[-1],axis=1))

In [ ]:
X.head()

    Age  Education Level  Years of Experience
0  32.0              0.0                  5.0
1  28.0              1.0                  3.0
2  45.0              2.0                 15.0
3  36.0              0.0                  7.0
4  52.0              1.0                 20.0

In [ ]:
Y.head()

     Salary
0   90000.0
1   65000.0
2  150000.0
3   60000.0
4  200000.0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state=12)

In [ ]:
reg = OLS(y_train, X_train).fit()

In [ ]:
y_pred = pd.DataFrame()   # dataframe for predictions vs actual y-values
y_pred['predictions'] = reg.predict(X_test)

# Print this directly
print(y_pred['predictions'])

269     90146.129700
1       62386.877421
71      99290.093249
78     165237.897707
21     159409.549427
           ...
137     55978.922274
35      43065.859207
289     58491.655286
37     130267.808024
150     50150.573993
Name: predictions, Length: 112, dtype: float64

In [ ]:
import numpy as np
data = pd.DataFrame({'Actual': y_test['Salary'], 'Predicted': y_pred["predictions"]})
diff = y_test['Salary'] - y_pred["predictions"]

data = data[np.abs(diff) <= 1000]

print(data)

       Actual      Predicted
369   60000.0   59748.021792
101   95000.0   94041.351835
244   70000.0   70148.351847
268   60000.0   59748.021792
285  150000.0  150845.192744
362  150000.0  150845.192744
295   60000.0   59748.021792

In [ ]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 12732.666517519201
Mean Squared Error: 284134880.2553149
Root Mean Squared Error: 16856.30090664363